//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mbrBlog.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleLabel = new HashSet<ArticleLabel>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PublicationTime { get; set; }
        public Nullable<int> PvCount { get; set; }
    
        public virtual ICollection<ArticleLabel> ArticleLabel { get; set; }
    }
}
